# Generated by Django 3.1 on 2024-02-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtuapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='corporate_data_vending_medium',
            field=models.CharField(choices=[('OGDAMS', 'OGDAMS'), ('SIM_SERVER', 'SIM_SERVER'), ('CLOUDSIMHOST', 'CLOUDSIMHOST'), ('UWS', 'UWS'), ('MSORG_DEVELOPED_WEBSITE', 'MSORG_DEVELOPED_WEBSITE'), ('MSORG_DEVELOPED_WEBSITE_1', 'MSORG_DEVELOPED_WEBSITE_1'), ('SMEPLUG', 'SMEPLUG'), ('SMS', 'SMS')], max_length=30),
        ),
        migrations.AlterField(
            model_name='network',
            name='gifting_data_vending_medium',
            field=models.CharField(blank=True, choices=[('OGDAMS', 'OGDAMS'), ('SIM_SERVER', 'SIM_SERVER'), ('CLOUDSIMHOST', 'CLOUDSIMHOST'), ('UWS', 'UWS'), ('MSORG_DEVELOPED_WEBSITE', 'MSORG_DEVELOPED_WEBSITE'), ('MSORG_DEVELOPED_WEBSITE_1', 'MSORG_DEVELOPED_WEBSITE_1'), ('SMEPLUG', 'SMEPLUG'), ('SMS', 'SMS')], max_length=30, null=True),
        ),
    ]
