# Generated by Django 3.1 on 2024-02-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtuapp', '0002_auto_20240221_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='corporate_data_vending_medium',
            field=models.CharField(choices=[('SMEPLUG', 'SMEPLUG'), ('CLOUDSIMHOST', 'CLOUDSIMHOST'), ('MSORG_DEVELOPED_WEBSITE', 'MSORG_DEVELOPED_WEBSITE'), ('SIM_SERVER', 'SIM_SERVER'), ('MSORG_DEVELOPED_WEBSITE_1', 'MSORG_DEVELOPED_WEBSITE_1'), ('OGDAMS', 'OGDAMS'), ('UWS', 'UWS'), ('SMS', 'SMS')], max_length=30),
        ),
        migrations.AlterField(
            model_name='network',
            name='gifting_data_vending_medium',
            field=models.CharField(blank=True, choices=[('SMEPLUG', 'SMEPLUG'), ('CLOUDSIMHOST', 'CLOUDSIMHOST'), ('MSORG_DEVELOPED_WEBSITE', 'MSORG_DEVELOPED_WEBSITE'), ('SIM_SERVER', 'SIM_SERVER'), ('MSORG_DEVELOPED_WEBSITE_1', 'MSORG_DEVELOPED_WEBSITE_1'), ('OGDAMS', 'OGDAMS'), ('UWS', 'UWS'), ('SMS', 'SMS')], max_length=30, null=True),
        ),
    ]
