# Generated by Django 3.1 on 2024-02-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtuapp', '0004_auto_20240221_2239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disable_Service',
        ),
        migrations.DeleteModel(
            name='Info_Alert',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Beginner', 'Beginner')], default='Beginner', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='data_type',
            field=models.CharField(blank=True, choices=[('CORPORATE', 'CORPORATE'), ('GIFTING', 'GIFTING'), ('SME', 'SME')], help_text='Select Plan Type SME or GIFTING or CORPORATE GIFTING', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('CORPORATE', 'CORPORATE'), ('GIFTING', 'GIFTING'), ('SME', 'SME')], help_text='Data plan  type only .', max_length=30),
        ),
    ]
