# Generated by Django 3.1 on 2024-02-21 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtuapp', '0005_auto_20240221_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_verify',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verify',
        ),
    ]
